### ISSUE TITLE
Connect history context to a ORM?

### ISSUE THREAD

**Issue by stegben** [ntucllab/striatum#18]
maybe we need a method call ```load_history```

**Comment by ianlini** [comment]
why?

**Comment by taweihuang** [comment]
there is a method called `get_history`, do you mean this?

**Comment by stegben** [comment]
The service may store history context in a database, so for different algorithm, they should access the database and load the context features if needed

**Comment by stegben** [comment]
@taweihuang no, ```get_history``` returns the history context stored in object (which is in memory temporarily). I would like to implement a ```load_history``` method to initialize model by adding old contexts from outside

**Comment by ianlini** [comment]
`get_history` should do this

**Comment by taweihuang** [comment]
If you mean that you need a method to query the table like this, I think you should add another class/function/etc rather than a method in the  `HistoryStorage` object .

![image](https://cloud.githubusercontent.com/assets/19475153/17127799/f8e69e98-533a-11e6-9d20-66a55c1aedee.png)

The `context` will combine both user and action features, and hence it will not always be the same even for the same action.
