### ISSUE TITLE
data structure of context

### ISSUE THREAD

**Issue by yangarbiter** [ntucllab/striatum#42]
The current data structure of context in history storage uses dictionary to
represent the context of each actions. Therefore there is a lot of dict.values()
dict.keys(). These two functions didn't seems to guarantee the order and it
causes a lot of bugs in python3. I recommended using list of list instead of
dict of dict to store it. Simply open another variable to store the name of
each action and context for each actions (I think the context for each action
should be the same?)

**Comment by taweihuang** [comment]
We should have different contexts for actions, but I'll try to use list instead of dictionary in this case.

**Comment by ianlini** [comment]
why list of list?

**Comment by ianlini** [comment]
You can use OrderedDict if the key of the dictionary is necessary

**Comment by ianlini** [comment]
You can use `six.viewvalues` and `six.viewkeys` to make python2 and python3 have the same behavior

**Comment by yangarbiter** [comment]
list of list or numpy.ndarray is more intuitive to me, since the key of the dictionary
is just some sort of name for each column or row.

**Comment by ianlini** [comment]
I don't think the columns are fixed, so it's hard to represent the context for one history. 
Also, the rows are frequently increased, so ndarray is not useful here.

**Comment by taweihuang** [comment]
I think list of lists is okay in this case since it's just like a dictionary (but a little bit bothering for getting action_id and contexts.) But ndarray is not proper (Ian had explained that).

 One thing I concern here is the order, but I've checked the 2.x and 3.x documents, and they say
` If keys, values and items views are iterated over with no intervening modifications to the dictionary, the order of items will directly correspond.`
So, I think we'll not meet the ordering problem in all algos even when the order is not the same as the input dictionary.

**Comment by ianlini** [comment]
where do we need to consider the order?

**Comment by yangarbiter** [comment]
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/exp4p.py#L158

This is where I think may cause problem.
The query_vector is a ndarray, though line 164 index it with something may not be a int.

**Comment by ianlini** [comment]
I think the ordering problems are solved. 
We can open another issue if we still have other thoughts about the context structure.
